### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by Xerbo** [Xerbo/satmap#1]
In local development:
- [ ] Cartopy for support of more projections (geomapping)
- [ ] Map overlay generation

In development branch:

Future:

Done:
- [x] OpenCV for transformation (georeferencing)
