### ISSUE TITLE
Progress Tracker (C++ version)

### ISSUE THREAD

**Issue by Xerbo** [Xerbo/satmap#6]
- [ ] Add base code
- [ ] TLE reading and predicting
- [ ] Image I/O with OpenCV
- [ ] Implement maths
- [ ] Mapping images
- [ ] Compensation for the bad geometry correction on APT
- [ ] Creating overlays
